export const badWords = [
    "anal",
    "anus",
    "arse",
    "ass",
    "balls",
    "bastard",
    "biatch",
    "bitch",
    "blow job",
    "boob",
    "bum",
    "butt",
    "buttplug",
    "clitoris",
    "cock",
    "dick",
    "dildo",
    "f u c k",
    "feck",
    "felching",
    "fellate",
    "fuck",
    "jerk",
    "jizz",
    "knob end",
    "knobend",
    "labia",
    "lmao",
    "lmfao",
    "pussy",
    "shit",
    "sex",
    "sh1t",
    "slut",
    "wank",
    "whore",
    "wtf",
    "porn",
    "fucking",
    "fucker",
    "fucked",
    "sister fucker",
    "mother fucker",
    "tits",
    "booty",
    "creampie",
    "gangbang",
    "milf",
    "asshole",
    "pornhub",
    "pornography",
    "boobs"
  ]
  